---
deployment:
  tasks:
    - cd /home/azwywnto/repositories/shopify-section-app-final && npm install --production=false
    - cd /home/azwywnto/repositories/shopify-section-app-final && npx prisma generate
    - cd /home/azwywnto/repositories/shopify-section-app-final && npm run build
